#!/bin/sh

lb config noauto --clean \
	--bootappend-live "homepage=http://webconverger.com hostname=webconverger nonetworking nopersistent quickreboot vga=normal video=vesa nomodeset splash quiet" \
	--parent-mirror-chroot "http://cdn.debian.net/debian/" \
	--parent-mirror-binary "http://cdn.debian.net/debian/" \
	-k 486 \
	-a i386 \
	-b iso-hybrid \
	--hostname webconverger \
	--parent-archive-areas "main contrib non-free" \
	--mode progress --distribution artax \
	--debian-installer false \
	--debian-installer-preseedfile config/binary_debian-installer/preseed.cfg \
	--syslinux-theme progress-appliance \
	--apt-indices false \
	--iso-publisher "http://webconverger.com" \
	--iso-volume "Webconverger" \
	--iso-application "Webconverger" \
	--archive-areas "main contrib non-free" \
	--apt-recommends false \
	--memtest none \
	--source false \
	--archives live \
	${@}
